app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2
  pg_url: 'postgres://localhost:5432/postgres'

cache_size: 128

jetstream:
  stream_name: 'ORDERS'
  stream_subjects: 'ORDERS.*'
  subject_name_order_created: 'ORDERS.received'